[package]
name = "makepad-android-state"
version = "0.4.0"
authors = ["Makepad <info@makepad.nl>", "Kevin Boos <kevinaboos@gmail.com>"]
edition = "2021"
description = "Tiny crate for exposing access to Makepad's context states on Android"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "ue5pTU0e_KaMiNqLQpo2CaD-WeQ="

[target.'cfg(target_os = "android")'.dependencies]
jni-sys = { path = "../../libs/jni-sys", version = "0.4.0" }
